### ISSUE TITLE
Issue-コイン管理画面、コイン情報編集機能の実装 #3

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#100]
Automated Review Comments
Issues in src/pages/assets-edit/assets-edit.ts:
  - (5, 'TODO found')
Issues in www/build/main.js:
  - (1, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (40, 'TODO found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
Issues in www/build/main.js.map:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'TODO found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
