### ISSUE TITLE
Issue-コイン管理画面、コイン登録処理の実装 #3

画面に合わせてmockサーバーの方に若干の処理の修正を行った。

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#106]
Automated Review Comments
Issues in ionic.config.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in mock/middlware.js:
  - (5, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in src/pages/assets-edit/assets-edit.html:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in src/pages/assets-edit/assets-edit.ts:
  - (9, 'TODO found')
  - (19, 'TODO found')
Issues in src/providers/rest/rest.ts:
  - (6, 'Line exceeds 80 characters')
Issues in www/build/main.js:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (22, 'TODO found')
  - (31, 'TODO found')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
Issues in www/build/main.js.map:
  - (2, 'TODO found')
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'TODO found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
