### ISSUE TITLE
Issue-総資産画面のネットワークエラー表示の処理を修正 #2

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#114]
Automated Review Comments
Issues in src/pages/assets-view/assets-view.html:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in src/pages/assets-view/assets-view.ts:
  - (7, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in src/providers/rest/rest.ts:
  - (7, 'Line exceeds 80 characters')
Issues in www/build/main.js:
  - (21, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
Issues in www/build/main.js.map:
  - (2, 'TODO found')
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'TODO found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
