### ISSUE TITLE
Issue-Ionic storageのインストールと追加

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#116]
Automated Review Comments
Issues in package.json:
  - (9, 'Hardcoded string found')
Issues in src/app/app.module.ts:
  - (1, 'Line exceeds 80 characters')
Issues in www/build/main.js:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
Issues in www/build/main.js.map:
  - (2, 'TODO found')
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'TODO found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
Issues in www/build/vendor.js:
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (156, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (170, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (193, 'Line exceeds 80 characters')
  - (201, 'Hardcoded string found')
  - (202, 'Line exceeds 80 characters')
  - (203, 'Hardcoded string found')
  - (204, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (206, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (208, 'Line exceeds 80 characters')
  - (224, 'Line exceeds 80 characters')
  - (227, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (235, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (245, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (262, 'Line exceeds 80 characters')
  - (272, 'Hardcoded string found')
  - (277, 'Line exceeds 80 characters')
  - (277, 'Hardcoded string found')
  - (295, 'Line exceeds 80 characters')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (373, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (552, 'Hardcoded string found')
  - (568, 'Line exceeds 80 characters')
  - (568, 'Hardcoded string found')
  - (574, 'Line exceeds 80 characters')
  - (574, 'Hardcoded string found')
  - (577, 'Line exceeds 80 characters')
  - (578, 'Line exceeds 80 characters')
  - (579, 'Hardcoded string found')
  - (622, 'Line exceeds 80 characters')
  - (622, 'Hardcoded string found')
  - (625, 'Hardcoded string found')
  - (626, 'Hardcoded string found')
  - (630, 'Line exceeds 80 characters')
  - (630, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (634, 'Line exceeds 80 characters')
  - (634, 'Hardcoded string found')
  - (636, 'Line exceeds 80 characters')
  - (636, 'Hardcoded string found')
  - (641, 'Hardcoded string found')
  - (644, 'Hardcoded string found')
  - (647, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (653, 'Hardcoded string found')
  - (677, 'Line exceeds 80 characters')
  - (677, 'Hardcoded string found')
  - (681, 'Hardcoded string found')
  - (686, 'Hardcoded string found')
  - (693, 'Hardcoded string found')
  - (698, 'Line exceeds 80 characters')
  - (698, 'Hardcoded string found')
  - (717, 'Hardcoded string found')
  - (720, 'Line exceeds 80 characters')
  - (720, 'Hardcoded string found')
  - (731, 'Hardcoded string found')
  - (747, 'Hardcoded string found')
  - (751, 'Hardcoded string found')
  - (752, 'Hardcoded string found')
  - (792, 'Line exceeds 80 characters')
  - (797, 'Hardcoded string found')
  - (811, 'Line exceeds 80 characters')
  - (812, 'Line exceeds 80 characters')
  - (814, 'Hardcoded string found')
  - (820, 'Hardcoded string found')
  - (895, 'Hardcoded string found')
  - (896, 'Line exceeds 80 characters')
  - (896, 'Hardcoded string found')
  - (936, 'Line exceeds 80 characters')
  - (936, 'Hardcoded string found')
  - (944, 'Hardcoded string found')
  - (1066, 'Hardcoded string found')
  - (1105, 'Hardcoded string found')
  - (1113, 'Line exceeds 80 characters')
  - (1113, 'Hardcoded string found')
  - (1130, 'Hardcoded string found')
  - (1144, 'Line exceeds 80 characters')
  - (1144, 'Hardcoded string found')
  - (1157, 'Line exceeds 80 characters')
  - (1162, 'Hardcoded string found')
  - (1172, 'Hardcoded string found')
  - (1184, 'Hardcoded string found')
  - (1194, 'Line exceeds 80 characters')
  - (1203, 'Line exceeds 80 characters')
  - (1203, 'Hardcoded string found')
  - (1218, 'Hardcoded string found')
  - (1233, 'Hardcoded string found')
  - (1244, 'Hardcoded string found')
  - (1252, 'Line exceeds 80 characters')
  - (1252, 'Hardcoded string found')
  - (1258, 'Hardcoded string found')
  - (1260, 'Hardcoded string found')
  - (1269, 'Line exceeds 80 characters')
  - (1275, 'Hardcoded string found')
  - (1288, 'Line exceeds 80 characters')
  - (1288, 'Hardcoded string found')
  - (1300, 'Hardcoded string found')
  - (1313, 'Line exceeds 80 characters')
  - (1313, 'Hardcoded string found')
  - (1323, 'Hardcoded string found')
  - (1342, 'Line exceeds 80 characters')
  - (1342, 'Hardcoded string found')
  - (1375, 'Hardcoded string found')
  - (1388, 'Line exceeds 80 characters')
  - (1388, 'Hardcoded string found')
  - (1402, 'Hardcoded string found')
  - (1408, 'Hardcoded string found')
  - (1416, 'Hardcoded string found')
  - (1428, 'Line exceeds 80 characters')
  - (1429, 'Line exceeds 80 characters')
  - (1431, 'Line exceeds 80 characters')
  - (1440, 'Hardcoded string found')
  - (1441, 'Hardcoded string found')
  - (1451, 'Line exceeds 80 characters')
  - (1499, 'Line exceeds 80 characters')
  - (1504, 'Line exceeds 80 characters')
  - (1506, 'Line exceeds 80 characters')
  - (1524, 'TODO found')
  - (1525, 'Line exceeds 80 characters')
  - (1556, 'Hardcoded string found')
  - (1567, 'Line exceeds 80 characters')
  - (1577, 'Line exceeds 80 characters')
  - (1604, 'Line exceeds 80 characters')
  - (1608, 'Line exceeds 80 characters')
  - (1672, 'Line exceeds 80 characters')
  - (1672, 'Hardcoded string found')
  - (1680, 'Line exceeds 80 characters')
  - (1687, 'Line exceeds 80 characters')
  - (1687, 'Hardcoded string found')
  - (1704, 'Hardcoded string found')
  - (1713, 'Line exceeds 80 characters')
  - (1714, 'Line exceeds 80 characters')
  - (1728, 'Hardcoded string found')
  - (1743, 'Line exceeds 80 characters')
  - (1772, 'Hardcoded string found')
  - (1783, 'Hardcoded string found')
  - (1791, 'Hardcoded string found')
  - (1806, 'Line exceeds 80 characters')
  - (1806, 'Hardcoded string found')
  - (1821, 'TODO found')
  - (1827, 'Hardcoded string found')
  - (1838, 'Hardcoded string found')
  - (1847, 'Line exceeds 80 characters')
  - (1847, 'Hardcoded string found')
  - (1854, 'Hardcoded string found')
  - (1862, 'TODO found')
  - (1870, 'Line exceeds 80 characters')
  - (1870, 'Hardcoded string found')
  - (1876, 'Hardcoded string found')
  - (1893, 'Line exceeds 80 characters')
  - (1902, 'Hardcoded string found')
  - (1915, 'TODO found')
  - (1923, 'Line exceeds 80 characters')
  - (1923, 'Hardcoded string found')
  - (1924, 'Line exceeds 80 characters')
  - (1930, 'Hardcoded string found')
  - (1944, 'Line exceeds 80 characters')
  - (1944, 'Hardcoded string found')
  - (1957, 'Hardcoded string found')
  - (1965, 'Hardcoded string found')
  - (2026, 'Hardcoded string found')
  - (2083, 'Line exceeds 80 characters')
  - (2128, 'Line exceeds 80 characters')
  - (2155, 'Hardcoded string found')
  - (2177, 'Hardcoded string found')
  - (2203, 'TODO found')
  - (2204, 'Line exceeds 80 characters')
  - (2204, 'Hardcoded string found')
  - (2219, 'Hardcoded string found')
  - (2237, 'Hardcoded string found')
  - (2238, 'Hardcoded string found')
  - (2239, 'Hardcoded string found')
  - (2242, 'Line exceeds 80 characters')
  - (2244, 'Line exceeds 80 characters')
  - (2244, 'Hardcoded string found')
  - (2249, 'Hardcoded string found')
  - (2253, 'Hardcoded string found')
  - (2260, 'Hardcoded string found')
  - (2277, 'Line exceeds 80 characters')
  - (2304, 'Line exceeds 80 characters')
  - (2341, 'Line exceeds 80 characters')
  - (2341, 'Hardcoded string found')
  - (2345, 'Line exceeds 80 characters')
  - (2349, 'Hardcoded string found')
  - (2358, 'Hardcoded string found')
  - (2363, 'Hardcoded string found')
  - (2374, 'Line exceeds 80 characters')
  - (2378, 'Line exceeds 80 characters')
  - (2379, 'Line exceeds 80 characters')
  - (2392, 'Line exceeds 80 characters')
  - (2395, 'Line exceeds 80 characters')
  - (2395, 'Hardcoded string found')
  - (2403, 'Line exceeds 80 characters')
  - (2403, 'Hardcoded string found')
  - (2406, 'Line exceeds 80 characters')
  - (2428, 'Line exceeds 80 characters')
  - (2471, 'Line exceeds 80 characters')
  - (2496, 'Line exceeds 80 characters')
  - (2502, 'Hardcoded string found')
  - (2506, 'Line exceeds 80 characters')
  - (2518, 'Line exceeds 80 characters')
  - (2518, 'Hardcoded string found')
  - (2533, 'Hardcoded string found')
  - (2548, 'Line exceeds 80 characters')
  - (2552, 'Line exceeds 80 characters')
  - (2563, 'Line exceeds 80 characters')
  - (2598, 'Hardcoded string found')
  - (2600, 'Hardcoded string found')
  - (2606, 'Line exceeds 80 characters')
  - (2606, 'Hardcoded string found')
  - (2607, 'Line exceeds 80 characters')
  - (2618, 'Line exceeds 80 characters')
  - (2618, 'Hardcoded string found')
  - (2619, 'Line exceeds 80 characters')
  - (2621, 'Line exceeds 80 characters')
  - (2626, 'Line exceeds 80 characters')
  - (2631, 'Hardcoded string found')
  - (2634, 'Hardcoded string found')
  - (2636, 'Hardcoded string found')
  - (2640, 'Hardcoded string found')
  - (2652, 'Line exceeds 80 characters')
  - (2652, 'Hardcoded string found')
  - (2665, 'Line exceeds 80 characters')
  - (2675, 'Line exceeds 80 characters')
  - (2675, 'Hardcoded string found')
  - (2679, 'Line exceeds 80 characters')
  - (2684, 'Hardcoded string found')
  - (2698, 'Line exceeds 80 characters')
  - (2698, 'Hardcoded string found')
  - (2711, 'Line exceeds 80 characters')
  - (2718, 'Hardcoded string found')
  - (2730, 'Line exceeds 80 characters')
  - (2730, 'Hardcoded string found')
  - (2736, 'Line exceeds 80 characters')
  - (2737, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (8, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.

**Comment by andreyfmc** [comment]
install this
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)
