### ISSUE TITLE
Issue-Home画面のnavbarにアプリロゴを追加 #8

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#118]
Automated Review Comments
Issues in src/pages/home/home.html:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
Issues in src/pages/home/home.ts:
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in www/build/0.js:
  - (8, 'Hardcoded string found')
Issues in www/build/1.js:
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in www/build/main.js:
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (163, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (208, 'Line exceeds 80 characters')
  - (209, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (211, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
  - (216, 'Line exceeds 80 characters')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (229, 'Line exceeds 80 characters')
  - (229, 'Hardcoded string found')
  - (234, 'Line exceeds 80 characters')
  - (234, 'Hardcoded string found')
  - (235, 'Line exceeds 80 characters')
  - (235, 'Hardcoded string found')
  - (236, 'Line exceeds 80 characters')
  - (236, 'Hardcoded string found')
  - (238, 'Line exceeds 80 characters')
  - (238, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (259, 'Line exceeds 80 characters')
  - (260, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (262, 'Line exceeds 80 characters')
  - (265, 'Line exceeds 80 characters')
  - (265, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Line exceeds 80 characters')
  - (275, 'Hardcoded string found')
  - (276, 'Line exceeds 80 characters')
  - (277, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (279, 'Line exceeds 80 characters')
  - (280, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (282, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (284, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (288, 'Line exceeds 80 characters')
  - (289, 'Line exceeds 80 characters')
  - (290, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')
  - (292, 'Line exceeds 80 characters')
  - (293, 'Line exceeds 80 characters')
  - (294, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (296, 'Line exceeds 80 characters')
  - (297, 'Line exceeds 80 characters')
  - (297, 'Hardcoded string found')
  - (298, 'Line exceeds 80 characters')
  - (308, 'Hardcoded string found')
  - (309, 'Line exceeds 80 characters')
  - (309, 'Hardcoded string found')
  - (310, 'Line exceeds 80 characters')
  - (310, 'Hardcoded string found')
  - (311, 'Line exceeds 80 characters')
  - (311, 'Hardcoded string found')
  - (312, 'Line exceeds 80 characters')
  - (312, 'Hardcoded string found')
  - (313, 'Line exceeds 80 characters')
  - (313, 'Hardcoded string found')
  - (315, 'Line exceeds 80 characters')
  - (315, 'Hardcoded string found')
  - (316, 'Line exceeds 80 characters')
  - (316, 'Hardcoded string found')
  - (318, 'Line exceeds 80 characters')
  - (318, 'Hardcoded string found')
  - (319, 'Line exceeds 80 characters')
  - (319, 'Hardcoded string found')
  - (320, 'Line exceeds 80 characters')
  - (320, 'Hardcoded string found')
  - (321, 'Line exceeds 80 characters')
  - (321, 'Hardcoded string found')
  - (324, 'Line exceeds 80 characters')
  - (324, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Line exceeds 80 characters')
  - (328, 'Hardcoded string found')
  - (329, 'Line exceeds 80 characters')
  - (329, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (331, 'Line exceeds 80 characters')
  - (331, 'Hardcoded string found')
  - (332, 'Line exceeds 80 characters')
  - (332, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (343, 'Line exceeds 80 characters')
  - (344, 'Line exceeds 80 characters')
  - (345, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (348, 'Line exceeds 80 characters')
  - (349, 'Line exceeds 80 characters')
  - (350, 'Line exceeds 80 characters')
  - (354, 'Line exceeds 80 characters')
  - (354, 'Hardcoded string found')
  - (355, 'Line exceeds 80 characters')
  - (355, 'Hardcoded string found')
  - (356, 'Line exceeds 80 characters')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (359, 'Line exceeds 80 characters')
  - (359, 'Hardcoded string found')
  - (361, 'Line exceeds 80 characters')
  - (361, 'Hardcoded string found')
  - (362, 'Line exceeds 80 characters')
  - (362, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Line exceeds 80 characters')
  - (377, 'Hardcoded string found')
  - (378, 'Line exceeds 80 characters')
  - (379, 'Line exceeds 80 characters')
  - (380, 'Line exceeds 80 characters')
  - (381, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (382, 'Hardcoded string found')
  - (383, 'Line exceeds 80 characters')
  - (387, 'Line exceeds 80 characters')
  - (387, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (406, 'Line exceeds 80 characters')
  - (406, 'Hardcoded string found')
  - (407, 'Line exceeds 80 characters')
  - (407, 'Hardcoded string found')
  - (409, 'Line exceeds 80 characters')
  - (409, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (425, 'Line exceeds 80 characters')
  - (425, 'Hardcoded string found')
  - (426, 'Line exceeds 80 characters')
  - (426, 'Hardcoded string found')
  - (427, 'Line exceeds 80 characters')
  - (427, 'Hardcoded string found')
Issues in www/build/main.js.map:
  - (2, 'TODO found')
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'TODO found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
