### ISSUE TITLE
Issue-ログイン前のHome画面の画面の用意 #10

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#120]
Automated Review Comments
Issues in src/pages/not-singed-home/not-singed-home.html:
  - (12, 'Hardcoded string found')
Issues in src/pages/not-singed-home/not-singed-home.ts:
  - (23, 'Hardcoded string found')
Issues in www/build/4.js:
  - (7, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in www/build/4.js.map:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in www/build/5.js:
  - (7, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in www/build/5.js.map:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in www/build/6.js:
  - (7, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in www/build/6.js.map:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
