### ISSUE TITLE
Issue-wwwディレクトリ以下を管理対象から外した

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#126]
Automated Review Comments
Issues in www/build/0.js:
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
Issues in www/build/0.js.map:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
Issues in www/build/1.js:
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
Issues in www/build/1.js.map:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
Issues in www/build/main.js:
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (105, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (163, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (186, 'Line exceeds 80 characters')
  - (187, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (190, 'Hardcoded string found')
  - (191, 'Line exceeds 80 characters')
  - (195, 'Line exceeds 80 characters')
  - (195, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (214, 'Line exceeds 80 characters')
  - (214, 'Hardcoded string found')
  - (215, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
  - (217, 'Line exceeds 80 characters')
  - (217, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Line exceeds 80 characters')
  - (278, 'Hardcoded string found')
  - (279, 'Line exceeds 80 characters')
  - (280, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (282, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (284, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (288, 'Line exceeds 80 characters')
  - (288, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (298, 'Line exceeds 80 characters')
  - (298, 'Hardcoded string found')
  - (299, 'Line exceeds 80 characters')
  - (300, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (302, 'Line exceeds 80 characters')
  - (303, 'Line exceeds 80 characters')
  - (304, 'Line exceeds 80 characters')
  - (304, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (315, 'Line exceeds 80 characters')
  - (316, 'Line exceeds 80 characters')
  - (317, 'Line exceeds 80 characters')
  - (318, 'Line exceeds 80 characters')
  - (321, 'Line exceeds 80 characters')
  - (321, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (331, 'Line exceeds 80 characters')
  - (331, 'Hardcoded string found')
  - (332, 'Line exceeds 80 characters')
  - (333, 'Line exceeds 80 characters')
  - (334, 'Line exceeds 80 characters')
  - (335, 'Line exceeds 80 characters')
  - (336, 'Line exceeds 80 characters')
  - (337, 'Line exceeds 80 characters')
  - (338, 'Line exceeds 80 characters')
  - (339, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (341, 'Line exceeds 80 characters')
  - (342, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (344, 'Line exceeds 80 characters')
  - (345, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (348, 'Line exceeds 80 characters')
  - (349, 'Line exceeds 80 characters')
  - (350, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
  - (353, 'Line exceeds 80 characters')
  - (354, 'Line exceeds 80 characters')
  - (355, 'Line exceeds 80 characters')
  - (356, 'Line exceeds 80 characters')
  - (357, 'Line exceeds 80 characters')
  - (358, 'Line exceeds 80 characters')
  - (359, 'Line exceeds 80 characters')
  - (359, 'Hardcoded string found')
  - (361, 'Line exceeds 80 characters')
  - (361, 'Hardcoded string found')
  - (362, 'Line exceeds 80 characters')
  - (362, 'Hardcoded string found')
  - (364, 'Line exceeds 80 characters')
  - (364, 'Hardcoded string found')
  - (365, 'Line exceeds 80 characters')
  - (365, 'Hardcoded string found')
  - (366, 'Line exceeds 80 characters')
  - (366, 'Hardcoded string found')
  - (367, 'Line exceeds 80 characters')
  - (367, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (379, 'Line exceeds 80 characters')
  - (379, 'Hardcoded string found')
  - (380, 'Line exceeds 80 characters')
  - (381, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (383, 'Line exceeds 80 characters')
  - (384, 'Line exceeds 80 characters')
  - (385, 'Line exceeds 80 characters')
  - (386, 'Line exceeds 80 characters')
  - (387, 'Line exceeds 80 characters')
  - (388, 'Line exceeds 80 characters')
  - (389, 'Line exceeds 80 characters')
  - (390, 'Line exceeds 80 characters')
  - (391, 'Line exceeds 80 characters')
  - (392, 'Line exceeds 80 characters')
  - (393, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (395, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (404, 'Line exceeds 80 characters')
  - (404, 'Hardcoded string found')
  - (405, 'Line exceeds 80 characters')
  - (406, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (409, 'Line exceeds 80 characters')
  - (409, 'Hardcoded string found')
  - (410, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (414, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (433, 'Line exceeds 80 characters')
  - (433, 'Hardcoded string found')
  - (434, 'Line exceeds 80 characters')
  - (434, 'Hardcoded string found')
  - (436, 'Line exceeds 80 characters')
  - (436, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (449, 'Line exceeds 80 characters')
  - (449, 'Hardcoded string found')
  - (450, 'Line exceeds 80 characters')
  - (451, 'Line exceeds 80 characters')
  - (452, 'Line exceeds 80 characters')
  - (453, 'Line exceeds 80 characters')
  - (454, 'Line exceeds 80 characters')
Issues in www/build/main.js.map:
  - (2, 'TODO found')
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'TODO found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
