### ISSUE TITLE
Issue-wwwディレクトリを管理下から削除

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#130]
Automated Review Comments
Issues in www/build/main.js:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
Issues in www/build/main.js.map:
  - (2, 'TODO found')
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'TODO found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
