### ISSUE TITLE
Issue-コイン価格リストの実装 #8

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#144]
Automated Review Comments
Issues in src/pages/home/home.html:
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
Issues in src/pages/home/home.ts:
  - (20, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
