### ISSUE TITLE
Issue-コイン価格リストのネットワークエラーの処理 #8

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#146]
Automated Review Comments
Issues in src/pages/home/home.html:
  - (8, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
