### ISSUE TITLE
Issue-未ログインHome画面のログインフォームの作成 #10

PC Viewの場合デカデカとロゴが表示されるため、CSSにwidth指定をしている

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#157]
Automated Review Comments
Issues in mock/mock-server.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
Issues in src/app/app.component.ts:
  - (12, 'Hardcoded string found')
Issues in src/app/app.module.ts:
  - (1, 'Line exceeds 80 characters')
Issues in src/pages/home/home.ts:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/pages/not-logged-home/not-logged-home.html:
  - (12, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
