### ISSUE TITLE
Issue-modify toggleGood func

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#169]
Automated Review Comments
Issues in mock/mock-server.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in package-lock.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/pages/article-post/article-post.html:
  - (12, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in src/pages/article-post/article-post.ts:
  - (29, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.html:
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.ts:
  - (3, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (80, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
