### ISSUE TITLE
Issue-add toggleBad func

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#173]
Automated Review Comments
Issues in mock/mock-server.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.ts:
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
