### ISSUE TITLE
Issue-Merge branch 'master' into checkpu

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#183]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (10, 'Hardcoded string found')
Issues in src/pages/not-logged-home/not-logged-home.html:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
