### ISSUE TITLE
Issue-delete useless code

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#187]
Automated Review Comments
Issues in src/pages/article-post/article-post.html:
  - (3, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.ts:
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
