### ISSUE TITLE
Issue-内部処理用のライブラリ・provider等の調整

- ハッシュ化するライブラリの追加
- パスワードをハッシュ化するproviderの追加
- WebSQL等を使えるようにするmoduleの追加

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#191]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/app/app.module.ts:
  - (29, 'Hardcoded string found')
Issues in src/providers/toHash/toHash.ts:
  - (2, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
