### ISSUE TITLE
Issue-add post func

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#195]
Automated Review Comments
Issues in mock/mock-server.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/app/app.module.ts:
  - (28, 'Hardcoded string found')
Issues in src/pages/article-post/article-post.html:
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in src/pages/article-post/article-post.ts:
  - (4, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.html:
  - (14, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.ts:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
Issues in src/pages/home/home.ts:
  - (12, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in src/pages/not-logged-home/not-logged-home.html:
  - (5, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in src/pages/not-logged-home/not-logged-home.ts:
  - (22, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
Issues in src/providers/rest/rest.ts:
  - (13, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
