### ISSUE TITLE
Issue-#13 の実装のためにMockサーバーのレスポンスを修正

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#199]
Automated Review Comments
Issues in mock/mock-server.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
Issues in src/pages/article-post/article-post.html:
  - (8, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
Issues in src/pages/article-post/article-post.ts:
  - (3, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.html:
  - (14, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.ts:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
