### ISSUE TITLE
Issue-Merge branch 'master' of github.com:CryptocurrencyApp/CryptocurrencyClient into post-article

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#203]
Automated Review Comments
Issues in mock/mock-server.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
