### ISSUE TITLE
Issue-create SignUpPage

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#208]
Automated Review Comments
Issues in src/app/app.module.ts:
  - (1, 'Line exceeds 80 characters')
Issues in src/pages/sign-up/sign-up.html:
  - (6, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
Issues in src/pages/sign-up/sign-up.ts:
  - (23, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
