### ISSUE TITLE
Issue-Merge branch 'master' of github-crypto-client:CryptocurrencyApp/CryptocurrencyClient

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#212]
Automated Review Comments
Issues in src/pages/article-post/article-post.ts:
  - (3, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
