### ISSUE TITLE
Issue-記事投稿画面で一回ミスると修正しても投稿できなかった問題を修正

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#216]
Automated Review Comments
Issues in src/pages/article-post/article-post.ts:
  - (13, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
