### ISSUE TITLE
Issue-投稿時刻と現在時刻の比較処理の実装（キャッチアップ画面） #14

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#224]
Automated Review Comments
Issues in src/pages/articles-view/articles-view.ts:
  - (27, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
