### ISSUE TITLE
Issue-Good/BadをクリックしたUIを変更（キャッチアップ画面） #4

クリックしたのかをわかりやすくして、より気持ち良い感じにした

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#226]
Automated Review Comments
Issues in src/pages/articles-view/articles-view.html:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
Issues in src/pages/articles-view/articles-view.ts:
  - (4, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
