### ISSUE TITLE
Issue-#14 の変更を適用 #13

コピペ実装なので、将来的に
コンポーネントとかにくくり出した方がいい気がする

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#232]
Automated Review Comments
Issues in src/pages/user-articles-view/user-articles-view.ts:
  - (5, 'TODO found')
  - (5, 'Hardcoded string found')
  - (6, 'TODO found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (17, 'TODO found')
  - (20, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
