### ISSUE TITLE
Issue-ユーザー情報表示画面の取得処理を作成 #16

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#244]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (19, 'Hardcoded string found')
Issues in src/app/app.module.ts:
  - (4, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in src/pages/user-detail/user-detail.html:
  - (12, 'Hardcoded string found')
Issues in src/pages/user-detail/user-detail.ts:
  - (25, 'TODO found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
