### ISSUE TITLE
Issue-Mockのユーザー情報にmailがなかったのを追加

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#246]
Automated Review Comments
Issues in mock/mock-server.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
