### ISSUE TITLE
Issue-Mockのユーザー情報のエンドポイントを修正

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#254]
Automated Review Comments
Issues in mock/mock-server.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in src/app/app.component.ts:
  - (1, 'Line exceeds 80 characters')
Issues in src/app/app.module.ts:
  - (1, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
