### ISSUE TITLE
Issue-Menu部分スタイルを編集

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#272]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (11, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
Issues in src/app/app.html:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
