### ISSUE TITLE
Issue-add userEditPage link

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#278]
Automated Review Comments
Issues in src/pages/user-detail/user-detail.html:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/pages/user-detail/user-detail.ts:
  - (1, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
