### ISSUE TITLE
Issue-Revert "modify storage code"

This reverts commit be1bbc081d8b9d5b66eb6a48c490f858d21e35b8.

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#284]
Automated Review Comments
Issues in mock/mock-server.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in src/app/app.component.ts:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/pages/user-articles-view/user-articles-view.ts:
  - (5, 'TODO found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/pages/user-detail/user-detail.ts:
  - (5, 'TODO found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in src/pages/user-edit/user-edit.ts:
  - (4, 'Line exceeds 80 characters')
  - (5, 'TODO found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
