### ISSUE TITLE
Issue-キャッチアップ画面のPCビューでのボタンの見た目に問題があったのを修正

ホバー時に色が変わってしまっていた。

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#292]
Automated Review Comments
Issues in src/pages/articles-view/articles-view.html:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
