### ISSUE TITLE
Issue-adapt beego:signup/login

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#300]
Automated Review Comments
Issues in src/pages/home/home.ts:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/pages/sign-up/sign-up.ts:
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in src/pages/user-edit/user-edit.ts:
  - (4, 'Line exceeds 80 characters')
  - (5, 'TODO found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
Issues in src/providers/rest/rest.ts:
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
