### ISSUE TITLE
Issue-adapt beego:usersEdit/userDetail

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#301]
Automated Review Comments
Issues in src/pages/home/home.ts:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/pages/not-logged-home/not-logged-home.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/pages/user-articles-view/user-articles-view.ts:
  - (5, 'TODO found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in src/pages/user-detail/user-detail.ts:
  - (13, 'TODO found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in src/pages/user-edit/user-edit.ts:
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
