### ISSUE TITLE
Issue-adapt beego:article

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#303]
Automated Review Comments
Issues in src/pages/article-post/article-post.ts:
  - (9, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.ts:
  - (8, 'TODO found')
  - (14, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
Issues in src/pages/home/home.ts:
  - (3, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
Issues in src/pages/user-articles-view/user-articles-view.html:
  - (3, 'Hardcoded string found')
Issues in src/pages/user-articles-view/user-articles-view.ts:
  - (8, 'TODO found')
  - (14, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
