### ISSUE TITLE
Issue-modify toggleGood/Bad func

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#313]
Automated Review Comments
Issues in src/pages/articles-view/articles-view.html:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.ts:
  - (8, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (43, 'TODO found')
  - (46, 'Line exceeds 80 characters')
  - (48, 'TODO found')
  - (51, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (129, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
