### ISSUE TITLE
Issue-modify storage load

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#315]
Automated Review Comments
Issues in src/pages/articles-view/articles-view.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (41, 'TODO found')
  - (44, 'Line exceeds 80 characters')
  - (46, 'TODO found')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
