### ISSUE TITLE
Issue-記事投稿画面にサイトタイトルとサイト名の追加

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#331]
Automated Review Comments
Issues in src/pages/articles-view/articles-view.html:
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
