### ISSUE TITLE
Issue-ログアウトの実装

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#335]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
