### ISSUE TITLE
Issue-アセット登録画面の追加

ionic generate pageで生成されたデフォルトのものにメニュートグルボタンとコンテンツを追記
ページ遷移を出来るようにアプリに対して登録

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#34]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in src/app/app.module.ts:
  - (1, 'Line exceeds 80 characters')
Issues in src/pages/asset-register/asset-register.html:
  - (12, 'Hardcoded string found')
Issues in src/pages/asset-register/asset-register.ts:
  - (22, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
