### ISSUE TITLE
Issue-主としたファイルの再フォーマット

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#38]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (15, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
Issues in src/app/app.html:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
Issues in src/pages/home/home.html:
  - (5, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
Issues in src/pages/list/list.html:
  - (5, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in src/pages/list/list.ts:
  - (19, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (42, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
