### ISSUE TITLE
Issue-アセット確認画面の追加・登録

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#40]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in src/app/app.module.ts:
  - (1, 'Line exceeds 80 characters')
Issues in src/pages/assets-view/assets-view.html:
  - (12, 'Hardcoded string found')
Issues in src/pages/assets-view/assets-view.ts:
  - (23, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
