### ISSUE TITLE
Issue-アセット編集画面の登録と確認画面からの移動経路追加

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#42]
Automated Review Comments
Issues in src/app/app.module.ts:
  - (17, 'Line exceeds 80 characters')
Issues in src/pages/assets-edit/assets-edit.html:
  - (12, 'Hardcoded string found')
Issues in src/pages/assets-edit/assets-edit.ts:
  - (23, 'Hardcoded string found')
Issues in src/pages/assets-view/assets-view.ts:
  - (18, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
