### ISSUE TITLE
Issue-アセット確認画面にFABボタンの追加 + アセット確認画面タイトルの変更 #2

アセット編集画面へのアクセスを行うボタンをFABボタン化し、画面の右下に表示するようにした

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#48]
Automated Review Comments
Issues in src/pages/assets-view/assets-view.html:
  - (3, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
