### ISSUE TITLE
Issue-総資産額表示カードの追加 + 編集ボタンの色変更 #2

総資産額を表示するカードを追加
総資産額カードをPrimary色にしたため、編集ボタンの色をSecondaryに降格

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#52]
Automated Review Comments
Issues in src/pages/assets-view/assets-view.html:
  - (5, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
