### ISSUE TITLE
Issue-アセット情報のMockデータを確認画面に描画 #2

- 必要となるAPIアクセスProviderを追加・getAssetsメソッドの定義
- 総資産額も計算し、描画するように修正

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#55]
Automated Review Comments
Issues in src/app/app.module.ts:
  - (10, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in src/pages/assets-view/assets-view.html:
  - (12, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in src/pages/assets-view/assets-view.ts:
  - (16, 'Line exceeds 80 characters')
Issues in src/providers/rest/rest.ts:
  - (16, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
