### ISSUE TITLE
Issue-`/coinIds` エンドポイントのMockのレスポンスを修正

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#64]
Automated Review Comments
Issues in mock/mock-server.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (422, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (436, 'Hardcoded string found')
  - (437, 'Hardcoded string found')
  - (440, 'Hardcoded string found')
  - (441, 'Hardcoded string found')
  - (442, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (460, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Hardcoded string found')
  - (472, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (482, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (495, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (497, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (502, 'Hardcoded string found')
  - (503, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (512, 'Hardcoded string found')
  - (513, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (518, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (521, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (525, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (527, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (531, 'Hardcoded string found')
  - (532, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (537, 'Hardcoded string found')
  - (538, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (545, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (555, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (557, 'Hardcoded string found')
  - (560, 'Hardcoded string found')
  - (561, 'Hardcoded string found')
  - (562, 'Hardcoded string found')
  - (563, 'Hardcoded string found')
  - (566, 'Hardcoded string found')
  - (567, 'Hardcoded string found')
  - (568, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (573, 'Hardcoded string found')
  - (574, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (579, 'Hardcoded string found')
  - (580, 'Hardcoded string found')
  - (581, 'Hardcoded string found')
  - (584, 'Hardcoded string found')
  - (585, 'Hardcoded string found')
  - (586, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
  - (590, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (592, 'Hardcoded string found')
  - (593, 'Hardcoded string found')
  - (596, 'Hardcoded string found')
  - (597, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (603, 'Hardcoded string found')
  - (604, 'Hardcoded string found')
  - (605, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (610, 'Hardcoded string found')
  - (611, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (615, 'Hardcoded string found')
  - (616, 'Hardcoded string found')
  - (617, 'Hardcoded string found')
  - (620, 'Hardcoded string found')
  - (621, 'Hardcoded string found')
  - (622, 'Hardcoded string found')
  - (623, 'Hardcoded string found')
  - (626, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
