### ISSUE TITLE
Issue-add nav_button to ArticlesView page

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#72]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.html:
  - (7, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
