### ISSUE TITLE
Issue-add ArticlePostPage

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#74]
Automated Review Comments
Issues in src/pages/article-post/article-post.html:
  - (12, 'Hardcoded string found')
Issues in src/pages/article-post/article-post.ts:
  - (23, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.html:
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in src/pages/articles-view/articles-view.ts:
  - (9, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
