### ISSUE TITLE
Issue-add kotori

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#76]
Automated Review Comments
Issues in src/pages/articles-view/articles-view.html:
  - (13, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
