### ISSUE TITLE
Issue-READMEのIonic用アクセス先Port番号が間違えていたのを修正

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#78]
Automated Review Comments
Issues in src/app/app.component.ts:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
