### ISSUE TITLE
Issue-コイン追加フォームを選択時に入力された文字列を消去する処理の追加 #3

input要素をngModel化した

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#80]
Automated Review Comments
Issues in src/pages/assets-edit/assets-edit.html:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in src/pages/assets-edit/assets-edit.ts:
  - (7, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
