### ISSUE TITLE
Issue-Mockサーバーの保存の前に処理を挟むように変更

middleware.jsを使って/assetsにPUTリクエストが来た場合にprice_jpyプロパティを追加するように変更
同時に、npm run mockでMockサーバーを起動できるようにスクリプトを追加

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#94]
Automated Review Comments
Issues in mock/middlware.js:
  - (7, 'Hardcoded string found')
Issues in mock/mock-server.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
