### ISSUE TITLE
Issue-middlewareの処理のミスを修正

String#splice()の使い方を間違えていた。

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/coin-pocket#96]
Automated Review Comments
Issues in mock/middlware.js:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in mock/mock-server.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
